version: '3.7'
services:
  discord:
    build: .
    container_name: 'discord'
    command: python3 main.py
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - TZ=Asia/Seoul